import './../styles/globals.css'
import Footer from './components/home/Footer'
import Navbar from './components/Navbar'
import Providers from './Provider'

export const metadata = {
  title: 'POST MASTER',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en" data-theme='light'>
      <body>
       <Providers>
         {/* Navbar */}
         <Navbar></Navbar>

{children}

{/* Footer */}
<Footer/>
       </Providers>
        </body>
    </html>
  )
}
